### ISSUE TITLE
Does not work on node.js version 4.5.0

### ISSUE THREAD

**Issue by agirorn** [create-oss/check-all-markdown#1]
When I try to run this module on node version 4.5.0 then I get the following error.

```
➜  doc git:(develop) ✗ ./node_modules/.bin/check-all-markdown source
/home/agirorn/code/doc/node_modules/check-all-markdown/scripts/check-all-markdown.js:15
  .then(([files, config]) =>
         ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

**Comment by giltayar** [comment]
True. This package supports only Node v6 and up.
